name: Ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install ruff
      run: |
        pip install ruff
        
    - name: Analysing the code with ruff    
      run: |
        ruff check .
